//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperCopa.Modelo
{
    using System;
    using System.ComponentModel;
    
    
    public enum Posicao : int
    {
        [Description("Atacante")]
        Atacante = 0,

        [Description("Zagueiro")]
        Zagueiro = 1,

        [Description("Goleiro")]
        Goleiro = 2,

        [Description("Lateral Esquerdo")]
        LateralEsquerdo = 3,

        [Description("Lateral Direito")]
        LateralDireiro = 4,

        [Description("Meio Campo")]
        MeioCampo = 5,

        [Description("Centro Avante")]
        CentroAvante = 6
    }
}
