//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperCopa.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SuperCopaModelContainer : DbContext
    {
        public SuperCopaModelContainer()
            : base("name=SuperCopaModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agente> AgenteSet { get; set; }
        public virtual DbSet<Jogador> JogadoresSet { get; set; }
        public virtual DbSet<Treinador> TreinadoresSet { get; set; }
        public virtual DbSet<Equipe> EquipesSet { get; set; }
    }
}
